### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by j3k0** [nodrock/ANE-Facebook#1]
Hey, thanks for taking over the unmaintained yet important Facebook ANE.

More a small request than an issue.

It's possible to associate your release with binary files on GitHub. Would be nice to have the compiled ANE up there :-)

Cheers!

**Comment by nodrock** [comment]
Thank you for your request. I will look into releases and deploy current release as soon as possible. I didn't want to commit ANE to git repository because the repo is huge enough (around 1GB).

**Comment by j3k0** [comment]
Yes, Freshplanet used to do binary-releases in the repo, bad idea! It'll probably benefit from a big flatting out...

I have been trying to compile the ANE for all evening with no luck. What's the status BTW, production ready?

**Comment by nodrock** [comment]
I uploaded initial release. You can try it. I am also considering to creating new repo with source codes only. Is there any way to remove binary files from git history? :) If you have problems with compilation please try to specify them more so I can fix them or change configuration to be more simple for others. Thank you

**Comment by nodrock** [comment]
For me this is absolutely production ready because I need to release one big project with this library. But I consider some other changes to API but when I do them I will write migration guide. (e.g. I don't like logIn\* callback declaration much. I would like to use more type safe mechanism.)

**Comment by j3k0** [comment]
Thanks for the binary. Still wouldn't compile, wondering if problem is from my config: i'll make another issue with that.

Will try out the release right away, and let you know.

Yes you can remove file from the history with `git --filter-branch`.

Examples here http://www.aberdeencloud.com/guides/services/repository/recover

**Comment by nodrock** [comment]
It was a lot of work but now the repo has around 80 MB. Thank you for info. I am closing this because binary anes are in releases and repo is clean enough.
