### ISSUE TITLE
App crash when another invoke event is caught.

### ISSUE THREAD

**Issue by OzanBarsal** [nodrock/ANE-Facebook#10]
I encountered a serious problem, when I try to open my app from a push notification when the app is at closed state causes it to crash as soon as facebook init is called on ios.

The crash happens right after I call Facebook.getInstance().init("123456789"); and only if I open the app from a push notification.

I use a INVOKE event listener to get the push data, which is also used in AS3 part of the Facebook ANE.

Adobe states that whenever you add a listener for invoke events, you'll get the previous invoke events, therefore a delayed call to the facebook init doesn't solve the issue.

I tried fixing the problem from as3 side by checking if the invoke event is for facebook by editing the Facebook.as class  by adding the code below, but it didn't fix it.

```
    if (event.reason == InvokeEventReason.NOTIFICATION)
    {
        Logger.log("Wrong Invoke Event was caught. Ignoring.");
        return;
    }
```

And flash console doesn't log anything prior to crash which got me into thinking it's a native code related issue.

I'm not using a native extension for push notifications, just as3. I haven't got any time to test it with the freshplanet push notification extension but if anyone tried using both extensions can you please test the issue there? If the app doesn't crash with the push notification extension I can switch to it.

I'm testing on AIR 17, iPhone 5s

Thanks.

**Comment by OzanBarsal** [comment]
Okay it seems my project was using the Facebook class from the ane. I had to change the package path in order to make my method work. I can use it without any problems right now.

**Comment by nodrock** [comment]
Okay I will close this issue then. If you had any problem let me know. Thank you

**Comment by nodrock** [comment]
It the same issue as #12 .
