### ISSUE TITLE
Missing check for InvokeEventReason.OPEN_URL in onInvoke() handler

### ISSUE THREAD

**Issue by OzanBarsal** [nodrock/ANE-Facebook#12]
I'm currently using your ane for both android and ios and I have a small problem.

When my app is opened through a push notification, the invoke event gets caught by the facebook ane from as3 side and calls the native ios code as if it has received data from facebook, which causes the app to crash as soon as Facebook.init is called.

My request from you is to simply add the following lines to the top of the invoke event listener function so that it doesn't handle notification invokes. And package the ane for me. 
I can't build the ane and if I use another class to handle facebook this time android throws me errors.

Here's the code i'd like you to add:

```
if (event.reason == InvokeEventReason.NOTIFICATION)
{
    log("Wrong Invoke Event was caught. Ignoring.");
    return;
}
```

Thanks in advance, Great work on the ane by the way.

**Comment by nodrock** [comment]
I will check this issue. Thank you

**Comment by nodrock** [comment]
I added check for InvokeEventReason.OPEN_URL in onInvoke() handler. These fix will be today in release.
