### ISSUE TITLE
Add Android-x86 support

### ISSUE THREAD

**Issue by dnikolaev** [nodrock/ANE-Facebook#13]
What about to add Android-x86 support? It's so simple.

`<arg line="-platform Android-x86 -platformoptions ../platform-android.xml -C android/ ."/>`

[build.xml](https://github.com/nodrock/ANE-Facebook/blob/master/build/build.xml)

```
<platform name="Android-x86">
    <applicationDeployment>
        <nativeLibrary>libAirFacebook.jar</nativeLibrary>
        <initializer>com.freshplanet.ane.AirFacebook.AirFacebookExtension</initializer>
        <finalizer>com.freshplanet.ane.AirFacebook.AirFacebookExtension</finalizer>
    </applicationDeployment>
</platform>
```

[extension.xml](https://github.com/nodrock/ANE-Facebook/blob/master/build/extension.xml)

That's all.

**Comment by nodrock** [comment]
I agree it will be in next release ;)
