### ISSUE TITLE
AppRequestDialog:null exception when parcel'd and frictionless friends

### ISSUE THREAD

**Issue by JohnHouston** [nodrock/ANE-Facebook#16]
While implementing the latest version with 4.5.3 and GameRequestContent, I have an issue where I am using the 'to' field.  To use the GameRequestContent, you must exclusively use 'to', 'filters' or 'suggestions' or validation will fail in the GameRequestValidation.  I can't use null in the filters value as that will cause a null reference exception when the GameRequestContent is parcel'd for the activity.  I have added the missing CREATOR, but now I am having to add some code to support a null filters value.

Also as a side note is it possible to implement frictionless app requests on android?  I was able to do this by setting a flag on the ios dialog, but don't see an easy way to do this with android. 

Thank you for your time,

--John

**Comment by nodrock** [comment]
I will check your issue and add pull request to FB api if there are missing CREATOR. I don't know how frictionless app requests works because I didn't implement this feature so I will read the documentation and let you know.

**Comment by nodrock** [comment]
FB added missing CREATOR in 4.6.0 version of FB Android SDK so I will update SDK.

**Comment by JohnHouston** [comment]
I did want to note that the Android SDK will take multiple 'to' param's.  The FBGameRequestContent::to array can be converted to a comma separated string and passed to the GameRequestContent::to string and the game request will be sent to multiple recipients.  Currently the GameRequestDialogFunction just passes the first element of the list.

```
// Android game request to do not support multiple targets. Use first target.
//if(to != null && to.size() > 0) builder.setTo(to.get(0));
if ( to != null && !to.isEmpty() ){
    StringBuilder joined = new StringBuilder();
    joined.append( to.get( 0 ) );
    for( int index = 1; index < to.size(); ++index ) {
        joined.append( ',' ).append( to.get( index  ) );
    }
    builder.setTo( joined.toString() );
}
```

thank you for your time and effort, it's much appreciated!

**Comment by nodrock** [comment]
@JohnHouston ouch sorry I didn't notice this comment so there is no fix for this. I will do it immediately and release fixed version.

**Comment by nodrock** [comment]
I will look into frictionless magic also.

**Comment by nodrock** [comment]
I created pull request to facebook sdk facebook/facebook-android-sdk#445. There are some issues with parceling that are connected to this issue. These changes are same in develop branch a15099a5a8eea4fd60a425758a256bb923b37fe8. I will wait for FB team reply and let you know.

**Comment by JohnHouston** [comment]
Thanks for the help, I had to add a bit of null checking to the parcel code so it could handle multiple null values.  Thanks again for all the work, the 4.6.0 was perfect timing as iOS9 just got released!

**Comment by nodrock** [comment]
Facebook merged pull request so I will make release soon with final code. I want to wait for one other pull request in FB iOS SDK where is an issue with OpenGraph.

**Comment by nodrock** [comment]
This issue is fixed. So I am closing it.

**Comment by JohnHouston** [comment]
Thanks for the work!  I am running this live now with good results!  Did Facebook ever get back about frictionless friends cache on Android?  Seems like it used to work a bit ago, possible pre 3.0.  Would be nice to have the same feel between iOS/Javascript and Android, now, only Android can't handle the frictionless friends.

(sorry for responding on a closed thread)
