### ISSUE TITLE
iOS app crash on facebookConnect

### ISSUE THREAD

**Issue by brookau** [nodrock/ANE-Facebook#18]
Please advise me anyone. I stuck with this issue for a while. I don't have much experience in flash builder. I don't know if it is possible to debug inside _context.call().

When I call this loginWithReadPermissions, the app crashed on 
Facebook.as:472 >>> _context.call('logInWithPermissions', permissions, type);

This is how I code.

> this._facebook.init("fb315498341803045", function ():void {
>                   trace("Done FACEBOOK initialized ");
>               });
> 
>  this._facebook.setLoginBehavior(FBLoginBehaviorIOS.WEB, FBLoginBehaviorAndroid.WEB_ONLY);
>  var permissions:Array = new Array();
>  permissions.push("email", "user_friends");  
>  this._facebook.logInWithReadPermissions(permissions, onConnected);

This is my iOS plist.

> ```
>     <InfoAdditions><![CDATA[
>       <key>UIDeviceFamily</key>
>       <array>
>           <string>1</string>
>           <string>2</string>
>       </array>
>       <key>CFBundleURLTypes</key>
>       <array>
>           <dict>
>               <key>CFBundleURLSchemes</key>
>                   <array>
>                       <string>fbxxx</string>
>                   </array>
>           </dict>
>       </array>
>       <key>FacebookAppID</key>
>           <string>fbxxx</string>
>       <key>FacebookDisplayName</key>
>           <string>AppNameOnFacebook</string>
>   ]]></InfoAdditions>
> ```

Test device information.
iOS ver 8.2 , 9.0.1
AIR SDK V18
I also had "-swf-version=29" in my additional compiler arguments.

**Comment by nodrock** [comment]
What kind of crash it is? Is it a null pointer exception or some kind of native crash? Do you have a stack trace? 

You should call these before any call to Facebook 

``` actionscript
Facebook.logEnabled = true;
Facebook.nativeLogEnabled = true;
_facebook = Facebook.getInstance();
_facebook.init();
```

and you can use [iosconsole](http://lemonjar.com/iosconsole/) to get logs from native code.

**Comment by brookau** [comment]
Hi, Thank you for a quick reply.
I just managed to fix that.

The problem is in my plist.

```
    <InfoAdditions><![CDATA[
        <key>UIDeviceFamily</key>
        <array>
            <string>1</string>
            <string>2</string>
        </array>
        <key>CFBundleURLTypes</key>
        <array>
            <dict>
                <key>CFBundleURLName</key>
                    <string>com.xxx.xxx</string>
                <key>CFBundleURLSchemes</key>
                    <array>
                        <string>fbxxx</string>
                    </array>
            </dict>
        </array>
        <key>FacebookAppID</key>
            <string>xxx</string>
        <key>FacebookDisplayName</key>
            <string>XXX</string>
        <key>NSAppTransportSecurity</key>
        <dict>
            <key>NSExceptionDomains</key>
            <dict>
                <key>facebook.com</key>
                <dict>
                    <key>NSIncludesSubdomains</key>
                    <true/>
                    <key>NSExceptionRequiresForwardSecrecy</key>
                    <false/>
                </dict>
                <key>fbcdn.net</key>
                <dict>
                    <key>NSIncludesSubdomains</key>
                    <true/>
                    <key>NSExceptionRequiresForwardSecrecy</key>
                    <false/>
                </dict>
                <key>akamaihd.net</key>
                <dict>
                    <key>NSIncludesSubdomains</key>
                    <true/>
                    <key>NSExceptionRequiresForwardSecrecy</key>
                    <false/>
                </dict>
            </dict>
        </dict>

        <key>LSApplicationQueriesSchemes</key>
        <array>
                <string>fbapi</string>
                <string>fb-messenger-api</string>
                <string>fbauth2</string>
                <string>fbshareextension</string>
        </array>
    ]]></InfoAdditions>
```

This is how it's look like now

Thank you again for your respond
