### ISSUE TITLE
Facebook.getInstance().accessToken return null on Android

### ISSUE THREAD

**Issue by nodrock** [nodrock/ANE-Facebook#5]
If you call Facebook.getInstance().accessToken immediately after Facebook.getInstance().init(), it always return null on Android, because Facebook call to Facebook.sdkInitialize() is async and Facebook don't provide callback in FB Android SDK 4.2. 

Workaround: Call init() as soon as possible and check for accessToken later. Or you can use setTimeout.

Solution: I will upgrade FB Android SDK to version 4.4 where Facebook added callback and I will provide it to you.

**Comment by dnikolaev** [comment]
We're waiting for commit :smile:

**Comment by nodrock** [comment]
Thanks for comment. I am almost done with [App Events](https://developers.facebook.com/docs/app-events/android) and then I will work on this. ETA 2-3 days. Anyway if you like this project you can star it for other programmers ;)
