### ISSUE TITLE
Graph API requests fail.

### ISSUE THREAD

**Issue by OzanBarsal** [nodrock/ANE-Facebook#9]
I'm having problems with getting data from Graph API, I can log the token, I can use the token in Graph API Explorer (https://developers.facebook.com/tools/explorer/), but when I try to use it in my app it returns this:

Object: { body: { error: { message: An active access token must be used to query information about the current user., type: OAuthException, code: 2500 } }, code: 400 }

I tried logOut then getting a new token still the same error every time.

Here's my code for logging in.

```
        Facebook.getInstance().init("{my_app_id}");

        Facebook.getInstance().logOut();  //For testing purposes.

        var permissions:Array = new Array();
        permissions.push("email", "user_birthday");

        Facebook.getInstance().setLoginBehavior(FBLoginBehaviorIOS.WEB, FBLoginBehaviorAndroid.WEB_ONLY);

        Facebook.getInstance().logInWithReadPermissions(permissions, onSessionRecieved);
```

And when I receive the session:

```
        Logger.log("session received : " + "success : " + success.toString() + " userCancelled : " + userCancelled.toString() +" error : " + error);
```

 // returns : session received : success : true userCancelled : false error : null

```
        Logger.log("Facebook Token : " + Facebook.getInstance().accessToken.tokenString);
```

// returns a working token which can be used in Graph API Explorer

Finally I do this

Facebook.getInstance().requestWithGraphPath("/me?fields=id,name,first_name,last_name,birthday,picture,email", null, "GET", onFacebookInfoRecieved);

AND BAM

{ body: { error: { message: An active access token must be used to query information about the current user., type: OAuthException, code: 2500 } }, code: 400 }

I need help here. Thanks.

**Comment by OzanBarsal** [comment]
I'm using it an Android by the way.

**Comment by nodrock** [comment]
Could you please try to use only /me to check if that's working and then try to put fileds into parameters object and see if that works. Thank you

**Comment by OzanBarsal** [comment]
Thank you so much for the fast answer. It worked when used as you said.

```
        var params:Object = { "fields":"id,name,first_name,last_name,birthday,picture,email" };

        Facebook.getInstance().requestWithGraphPath("/me", params, "GET", onFacebookInfoRecieved);
```

Here's a sample if anyone else has the same problem.

**Comment by nodrock** [comment]
Thanks I will close this issue.
